name = "tunewrap-web"
pages_build_output_dir = "."
compatibility_date = "2026-08-08"

[vars]
ENVIRONMENT = "production"
ACCESS_TEAM_DOMAIN = "https://dry-wave-888f.cloudflareaccess.com"
ACCESS_AUD = "bf1c62c77d9334188b6af53f721408414a97ed8ac13cd6edb94e9df0509dd7b6"

[[d1_databases]]
binding = "TUNEWRAP_DB"
database_name = "tunewrap-catalog"
database_id = "13604674-c5dc-4fc3-92cb-62d0eb39582c"
preview_database_id = "TUNEWRAP_DB"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "TUNEWRAP_MEDIA"
bucket_name = "tunewrap-media"
preview_bucket_name = "tunewrap-media-local"
