const LOCALES=[['en','EN'],['ru','RU'],['uk','UA'],['ka','GE'],['de','DE']];
const $=selector=>document.querySelector(selector);
const state={config:null,busy:false,dirty:false,updatedAt:'',lastEditedBy:''};
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function toast(message,error=false){const node=el('div','toast'+(error?' is-error':''),message);$('#toastRegion').append(node);setTimeout(()=>node.remove(),4200);}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set('accept','application/json');if(options.body)headers.set('content-type','application/json');const response=await fetch(path,{...options,headers,body:options.body?JSON.stringify(options.body):undefined});let payload=null;try{payload=await response.json();}catch(error){}if(!response.ok)throw new Error(payload?.error||`HTTP ${response.status}`);return payload;}
function slugify(value){const map={а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'yo',ж:'zh',з:'z',и:'i',й:'y',к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',х:'kh',ц:'ts',ч:'ch',ш:'sh',щ:'shch',ы:'y',э:'e',ю:'yu',я:'ya',ь:'',ъ:''};let output='';for(const char of String(value||'').trim().toLowerCase()){if(/[a-z0-9]/.test(char))output+=char;else if(Object.prototype.hasOwnProperty.call(map,char))output+=map[char];else output+='-';}output=output.replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);return output||`category-${Date.now().toString(36)}`;}
function setDirty(value=true){state.dirty=value;$('#saveState').textContent=value?'Есть несохранённые изменения':'Все изменения сохранены';}
function sorted(){return (state.config?.categories||[]).slice().sort((a,b)=>(a.order||99)-(b.order||99)||a.id.localeCompare(b.id));}
function normalizeOrders(){sorted().forEach((item,index)=>item.order=index+1);}
function localizedTitle(item){return item.labels?.ru||item.labels?.en||item.id;}
function updateItem(id,patch){const item=state.config.categories.find(value=>value.id===id);if(!item)return;Object.assign(item,patch);setDirty();}
function moveItem(id,direction){const items=sorted();const index=items.findIndex(item=>item.id===id);const target=index+direction;if(index<0||target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];items.forEach((item,order)=>item.order=order+1);state.config.categories=items;setDirty();render();}
function deleteItem(id){const item=state.config.categories.find(value=>value.id===id);if(!item)return;if(!confirm(`Удалить категорию «${localizedTitle(item)}»?\n\nОна будет снята и с треков, где была выбрана.`))return;state.config.categories=state.config.categories.filter(value=>value.id!==id);normalizeOrders();setDirty();render();}
function localeField(item,locale,label){const wrap=el('label','category-locale-field');wrap.append(el('span','',label));const input=document.createElement('input');input.type='text';input.maxLength=100;input.value=item.labels?.[locale]||'';input.placeholder=locale==='ru'?'Название':'—';input.addEventListener('input',()=>{item.labels={...(item.labels||{})};if(input.value.trim())item.labels[locale]=input.value.trim();else delete item.labels[locale];setDirty();if(locale==='ru'){const title=wrap.closest('.category-editor-row')?.querySelector('.category-identity strong');if(title)title.textContent=localizedTitle(item);}});wrap.append(input);return wrap;}
function categoryRow(item){const row=el('article','category-editor-row');row.dataset.categoryId=item.id;const identity=el('div','category-identity');identity.append(el('strong','',localizedTitle(item)),el('span','category-id',item.id));const enabled=el('label','category-enabled');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=item.enabled!==false;checkbox.addEventListener('change',()=>updateItem(item.id,{enabled:checkbox.checked}));enabled.append(checkbox,document.createTextNode('Показывать на сайте'));identity.append(enabled);const locales=el('div','category-locales');LOCALES.forEach(([locale,label])=>locales.append(localeField(item,locale,label)));const actions=el('div','category-order');const up=el('button','','↑');up.type='button';up.title='Выше';up.addEventListener('click',()=>moveItem(item.id,-1));const down=el('button','','↓');down.type='button';down.title='Ниже';down.addEventListener('click',()=>moveItem(item.id,1));const remove=el('button','category-delete','Удалить');remove.type='button';remove.addEventListener('click',()=>deleteItem(item.id));actions.append(up,down,remove);row.append(identity,locales,actions);return row;}
function render(){const items=sorted();$('#categoryList').replaceChildren(...items.map(categoryRow));$('#categoryEmpty').hidden=items.length>0;$('#saveMeta').textContent=state.updatedAt?`Обновлено ${new Date(state.updatedAt).toLocaleString('ru-RU')}${state.lastEditedBy?` · ${state.lastEditedBy}`:''}`:'—';}
async function load(){try{const result=await api('/api/admin/story-categories');state.config=result.config;state.updatedAt=result.updatedAt||'';state.lastEditedBy=result.lastEditedBy||'';setDirty(false);render();}catch(error){toast(error.message,true);}}
function addCategory(){const input=$('#newCategoryLabel');const label=input.value.trim();if(!label)return toast('Введите название новой категории',true);let id=slugify(label);const used=new Set((state.config.categories||[]).map(item=>item.id));const base=id;let suffix=2;while(used.has(id))id=`${base}-${suffix++}`;state.config.categories.push({id,enabled:true,order:state.config.categories.length+1,labels:{ru:label}});input.value='';setDirty();render();document.querySelector(`[data-category-id="${CSS.escape(id)}"] input`)?.focus();}
async function translateMissing(){if(state.busy)return;const items=state.config.categories||[];const withRu=items.filter(item=>item.labels?.ru);if(!withRu.length)return toast('Сначала добавьте русские названия',true);state.busy=true;$('#translateCategoriesButton').disabled=true;try{for(const [target,label] of LOCALES.filter(([locale])=>locale!=='ru')){const pending=withRu.filter(item=>!item.labels?.[target]);if(!pending.length)continue;for(let offset=0;offset<pending.length;offset+=8){const chunk=pending.slice(offset,offset+8);const result=await api('/api/admin/translate',{method:'POST',body:{sourceLanguage:'RU',target,items:chunk.map(item=>({id:item.id,kind:'text',text:item.labels.ru}))}});for(const item of chunk){const translated=String(result.translations?.[item.id]||'').trim();if(translated)item.labels={...(item.labels||{}),[target]:translated};}}toast(`Перевод ${label} готов`);}setDirty();render();}catch(error){toast(error.message,true);}finally{state.busy=false;$('#translateCategoriesButton').disabled=false;}}
async function save(){if(state.busy)return;state.busy=true;document.querySelectorAll('button').forEach(button=>button.disabled=true);try{normalizeOrders();const result=await api('/api/admin/story-categories',{method:'PUT',body:{config:state.config}});state.config=result.config;state.updatedAt=result.updatedAt||new Date().toISOString();state.lastEditedBy=result.lastEditedBy||'';setDirty(false);render();toast('Категории сохранены');}catch(error){toast(error.message,true);}finally{state.busy=false;document.querySelectorAll('button').forEach(button=>button.disabled=false);}}
$('#addCategoryButton').addEventListener('click',addCategory);$('#newCategoryLabel').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();addCategory();}});$('#translateCategoriesButton').addEventListener('click',translateMissing);$('#saveCategoriesButton').addEventListener('click',save);$('#saveCategoriesBottomButton').addEventListener('click',save);window.addEventListener('beforeunload',event=>{if(!state.dirty)return;event.preventDefault();event.returnValue='';});load();
