#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const {
  commandAvailable,
  formatResult,
  listPackages,
  validatePackage
} = require('./lib/track-tools');
const Core = require('../js/catalog-core.js');

const projectRoot = path.resolve(__dirname,'..');
const tracksRoot = path.join(projectRoot,'content/tracks');
const jsonOutput = path.join(projectRoot,'data/track-catalog.json');
const jsOutput = path.join(projectRoot,'js/track-catalog.generated.js');
const checkOnly = process.argv.includes('--check');
const diagnostic = process.argv.includes('--diagnostic');
const probe = commandAvailable('ffprobe');

if(!probe) console.warn('WARNING: ffprobe is unavailable; MP3 and artwork media inspection was skipped');

const results = listPackages(tracksRoot).map(packageDir => validatePackage(projectRoot,packageDir,{probe}));
const messages = results.flatMap(formatResult);
messages.forEach(message => console.log(message));

const duplicateIds = new Map();
for(const result of results){
  if(!result.track) continue;
  const existing = duplicateIds.get(result.track.id);
  if(existing){
    result.errors.push('Duplicate track id: ' + result.track.id + ' (also in ' + existing + ')');
    console.error('ERROR: ' + result.folder + '\n  Duplicate track id: ' + result.track.id);
  } else duplicateIds.set(result.track.id,result.folder);
}

const duplicateOrders = new Map();
for(const result of results){
  if(!result.track || !result.track.published) continue;
  const orderKey = result.track.section + ':' + result.track.order;
  const existing = duplicateOrders.get(orderKey);
  if(existing){
    result.errors.push('Duplicate published order in ' + result.track.section + ': ' + result.track.order);
    console.error('ERROR: ' + result.folder + '\n  Duplicate published order ' + result.track.order + ' in ' + result.track.section + ' (also used by ' + existing + ')');
  } else duplicateOrders.set(orderKey,result.track.id);
}

const featuredSections = new Map();
for(const result of results){
  const track = result.track;
  if(!track?.published || !track.featured) continue;
  if(featuredSections.has(track.section)){
    result.errors.push('Only one published featured track is allowed per section');
    console.error('ERROR: ' + result.folder + '\n  Multiple featured tracks in section: ' + track.section);
  } else featuredSections.set(track.section,track.id);
}

const errorCount = results.reduce((count,result) => count + result.errors.length,0);
if(errorCount){
  console.error('\nCatalog build failed with ' + errorCount + ' error(s).');
  process.exit(1);
}

const sectionRank = new Map(Core.SECTION_ORDER.map((section,index) => [section,index]));
const catalog = results.map(result => result.track).sort((left,right) =>
  (sectionRank.get(left.section) ?? Number.MAX_SAFE_INTEGER) - (sectionRank.get(right.section) ?? Number.MAX_SAFE_INTEGER) ||
  left.order - right.order ||
  left.id.localeCompare(right.id)
);
const playable = catalog.filter(track => track.published && track.audio);
const playbackQueue = Core.queue(Core.createCatalog(catalog));
const queueIds = playbackQueue.map(track => track.id);
const queueErrors = [];
if(playbackQueue.length !== playable.length){
  queueErrors.push('Global queue length (' + playbackQueue.length + ') does not match published playable tracks (' + playable.length + ')');
}
if(new Set(queueIds).size !== playbackQueue.length){
  queueErrors.push('Global queue contains duplicate track IDs');
}
const firstAuthorIndex = playbackQueue.findIndex(track => track.section === 'author');
if(firstAuthorIndex >= 0 && playbackQueue.slice(0,firstAuthorIndex).some(track => track.section !== 'stories')){
  queueErrors.push('A non-Story track appears before the Author boundary');
}
if(firstAuthorIndex >= 0 && playbackQueue.slice(firstAuthorIndex).some(track => track.section !== 'author')){
  queueErrors.push('A Story track appears after the Author boundary');
}
if(queueErrors.length){
  queueErrors.forEach(message => console.error('ERROR: ' + message));
  console.error('\nCatalog build failed queue validation.');
  process.exit(1);
}
const json = JSON.stringify({
  schemaVersion:1,
  generatedAt:new Date().toISOString(),
  trackCount:catalog.length,
  publishedCount:catalog.filter(track => track.published).length,
  tracks:catalog
},null,2) + '\n';
const browserJson = JSON.stringify(catalog).replace(/</g,'\\u003c');
const javascript = '/* Generated by npm run tracks:build. Do not edit manually. */\n' +
  '(function(){"use strict";window.TUNEWRAP_TRACK_CATALOG=' + browserJson + ';})();\n';

if(checkOnly){
  const currentJson = fs.existsSync(jsonOutput) ? JSON.parse(fs.readFileSync(jsonOutput,'utf8')) : null;
  const currentJs = fs.existsSync(jsOutput) ? fs.readFileSync(jsOutput,'utf8') : '';
  const comparable = currentJson && JSON.stringify(currentJson.tracks) === JSON.stringify(catalog);
  if(!comparable || currentJs !== javascript){
    console.error('ERROR: Generated Track Catalog is stale. Run npm run tracks:build.');
    process.exit(1);
  }
  console.log('VALID: ' + catalog.length + ' track package(s); generated catalog is current.');
  if(diagnostic) printQueueDiagnostic(playbackQueue);
  process.exit(0);
}

fs.mkdirSync(path.dirname(jsonOutput),{recursive:true});
fs.writeFileSync(jsonOutput,json);
fs.writeFileSync(jsOutput,javascript);
console.log('\nVALID: ' + catalog.length + ' track package(s), ' + catalog.filter(track => track.published).length + ' published.');
console.log('Generated data/track-catalog.json and js/track-catalog.generated.js');
if(diagnostic) printQueueDiagnostic(playbackQueue);

function printQueueDiagnostic(queue){
  const stories = queue.filter(track => track.section === 'stories');
  const author = queue.filter(track => track.section === 'author');
  console.log('\nGLOBAL PLAYBACK QUEUE');
  queue.forEach((track,index) => {
    console.log(String(index + 1).padStart(2,'0') + '. [' + track.section.toUpperCase() + '] ' + track.id);
  });
  console.log('STORIES: ' + stories.length + ' tracks');
  console.log('AUTHOR: ' + author.length + ' tracks');
  console.log('TOTAL: ' + queue.length);
}
